server:
  port: 5003

spring:
  jpa:
    #PostgreSQL settings
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    #MySQL jpa
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #show-sql: true
    #hibernate:
      #ddl-auto: update
  datasource:
    #PostgreSQL datasource
    url: jdbc:postgresql://localhost:5432/votingEventCollection
    username: postgres
    password: ioana
    #MySQL datasource
    #url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    #username: root
    #password: ioana
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: votingEventConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'